apiVersion: v1
kind: Service
metadata:
  labels:
    app: elasticsearch
  name: elasticsearch
spec:
  ports:
  - name: rest-port
    port: 9200
    targetPort: rest-port
  - name: nodes-port
    port: 9300
    targetPort: nodes-port
  selector:
    app: elasticsearch
