apiVersion: v1
data:
  elasticsearch.yml: |-
    ---
    cluster.name: "elk-cluster"
    network.host: 0.0.0.0

    xpack.license.self_generated.type: trial
    xpack.security.enabled: true
    xpack.monitoring.collection.enabled: true
kind: ConfigMap
metadata:
  name: elastic-config
