apiVersion: v1
data:
  kibana.yml: |-
    ---
      server.name: kibana
      server.host: "0"
      elasticsearch.hosts: [ "http://elasticsearch:9200" ]
      xpack.monitoring.ui.container.elasticsearch.enabled: true
      
      ## X-Pack security credentials
      elasticsearch.username: elastic
      elasticsearch.password: changeme
kind: ConfigMap
metadata:
  name: kibana-config
