annotations: {}

volume:
  storageClass: ""
  size: 5
  path: /home/mgeweb/compartilhado/elk/

user:
  uid: 1001


loadBalancer:
  dns: "orcl.jivacloud.com.br"

elk:
  version: 7.6.2

elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch
  cpu: "300m"
  memory: "3072Mi"
  java:
    opts: -Xms2g -Xmx2g
  
kibana:
  image: docker.elastic.co/kibana/kibana

logstash:
  image: docker.elastic.co/logstash/logstash
  java:
    opts: -Xmx512m -Xms512m
  

    
